// <auto-generated />
using System;
using Car2Go.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Car2Go.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220604094844_added-dealer")]
    partial class addeddealer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Car2Go.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Car2Go.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b5c0a153-575a-423e-bcfc-f463ebcf8c99",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad36d70d-b84a-4eb8-aa9d-a33c71d1ccee",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBgR9nXPZs6euU3fSHsL6rCRUnNYQU+oQRZBA8GxR67bYDc4k8NMqN4Uuazz0Jz8kA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b8f8afd-ec4b-4ae7-ab6e-1adc7a69a44b",
                            TwoFactorEnabled = false,
                            UserName = "Admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Car2Go.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DealerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GearType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InUse")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(4401),
                            Description = "Chevrolet Cobalt is a family sedan created by the designers of the Brazilian division of the GM Corporation using standard GM global development processes. Cobalt was developed by GM's global team to become the world benchmark in its segment and the leader in sales in growing markets. Chevrolet Cobalt combines comfort, sophistication and high dynamic qualities, as well as timeless traditional classic design. To ensure better safety, the Chevrolet Cobalt, manufactured from high-strength steel, is equipped with ABS (anti-lock braking system) and driver and front passenger airbags",
                            GearType = 2,
                            Image = "https://uzautomotors.com/images/uploads/ca519572d01038ee51311f82f9384204.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "Cobalt",
                            PricePerDay = 180000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(5894),
                            Description = "",
                            GearType = 0,
                            Image = "https://tasinha-photos-kluz.kcdn.online/webp/79/79646cb0-2e11-49b9-ae7a-50454c50b56c/1-160x120.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "Cobalt",
                            PricePerDay = 170000m,
                            Speed = 200,
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(5961),
                            Description = "The Nexia is one of the most compact, stylish and popular cars in the world, combining a sporty look and a spacious, comfortable interior. It is easy to operate and has a high-tech security system. Quality interior decoration materials are carefully thought out to the smallest detail. The large luggage allows you to take everything you need with you on the trip without sacrificing anything.",
                            GearType = 1,
                            Image = "https://uzautomotors.com/images/uploads/e2d6a236bd002eb0ce3b4b7613f009c7.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "Nexia 3",
                            PricePerDay = 150000m,
                            Speed = 180,
                            Year = 2020
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6022),
                            Description = "good",
                            GearType = 0,
                            Image = "https://tasinha-photos-kluz.kcdn.online/webp/04/04f10e23-aff0-4388-86d0-62bd87f06ad5/1-160x120.jpg",
                            InUse = true,
                            IsDeleted = false,
                            Model = "Nexia 3",
                            PricePerDay = 170000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6041),
                            Description = "Designers, working on a new generation of Chevrolet Malibu, tried to give the model more aggressiveness in the exterior. The novelty, unlike the previous generation, has a completely different exterior design. The presence of broken lines and bends gives the sedan a dynamic and makes it particularly attractive. The dual easy-to-recognize branded Malibu radiator grille is now equipped with a narrower head LED optics. The relief impressions on the sides of the body together with the rear part are similar in many respects to the Impala sedan, but in general the majority of the body elements are similar to the legendary Camaro, but it is only externally. At the same time, due to careful study of individual body parts, it was possible to achieve excellent aerodynamic performance. In the Uzbek market the car will be presented in 4 colors (pearl white, white-smoky, dark gray and black).",
                            GearType = 2,
                            Image = "https://uzautomotors.com/images/uploads/60e102ca38452ea6ba25541824d9d045.jpg",
                            InUse = true,
                            IsDeleted = false,
                            Model = "Malibu",
                            PricePerDay = 300000m,
                            Speed = 220,
                            Year = 2020
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6060),
                            Description = "",
                            GearType = 0,
                            Image = "https://tasinha-photos-kluz.kcdn.online/webp/2f/2fcac581-4e12-4d0c-b062-84db5ecadf37/5-160x120.jpg",
                            InUse = true,
                            IsDeleted = false,
                            Model = "Malibu",
                            PricePerDay = 280000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6076),
                            Description = "The Chevrolet Tracker is an automotive nameplate that has been used by Chevrolet for two different vehicle lines. Chevrolet Tracker (Americas): since 1988 for the 1989 model year, spanning two generations, Chevrolet has rebadged a version of the Suzuki Escudo as the Tracker.",
                            GearType = 2,
                            Image = "https://i.ibb.co/PF4pxf1/52.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "Chevrolet Tracker 2",
                            PricePerDay = 310000m,
                            Speed = 245,
                            Year = 2019
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6091),
                            Description = "",
                            GearType = 0,
                            Image = "https://www.autostrada.uz/wp-content/uploads/2020/12/20210115_123901-001.jpg",
                            InUse = true,
                            IsDeleted = false,
                            Model = "Chevrolet Tracker 2",
                            PricePerDay = 300000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6107),
                            Description = "The Chevrolet Tracker is an automotive nameplate that has been used by Chevrolet for two different vehicle lines. Chevrolet Tracker (Americas): since 1988 for the 1989 model year, spanning two generations, Chevrolet has rebadged a version of the Suzuki Escudo as the Tracker.",
                            GearType = 2,
                            Image = "https://uzautomotors.com/images/uploads/c892a6c45990f70c4531efb3b1c95a68.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "Chevrolet Tracker",
                            PricePerDay = 310000m,
                            Speed = 220,
                            Year = 2020
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6124),
                            Description = "",
                            GearType = 0,
                            Image = "https://auto.ironhorse.ru/wp-content/uploads/2017/06/Tracker-New.jpg",
                            InUse = true,
                            IsDeleted = false,
                            Model = "Chevrolet Tracker",
                            PricePerDay = 350000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6139),
                            Description = "The Optima is a vehicle that delivers all of these virtues in a stylish, value-laden package that’s filled with features usually found on pricier cars. With outstanding reliability and extensive warranty coverage, savvy sedan shoppers should take this recently redesigned car for a test drive.",
                            GearType = 2,
                            Image = "https://i.dir-i.net/CMS/2019/12/28/k/5f_kzmt31.jpg",
                            InUse = true,
                            IsDeleted = false,
                            Model = "Kia Optima",
                            PricePerDay = 350000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6154),
                            Description = "",
                            GearType = 0,
                            Image = "https://www.motortrend.com/uploads/sites/5/2018/10/2019-Kia-Optima-SX-front-three-quarter-in-motion-3.jpg",
                            InUse = true,
                            IsDeleted = false,
                            Model = "Kia Optima",
                            PricePerDay = 260000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6170),
                            Description = "And the most interesting is the motor range. The two-liter car is equipped with a nine-speed automatic, and the other two with a six-speed automatic. Drive - front or full. The fuel tank has a volume of 55 l, a 2.0 Turbo engine, consumption starts from 8.2 l / 100 km in the urban cycle. Acceleration time of the Chevrolet Equinox is 7.8 s to 100 km / h.",
                            GearType = 1,
                            Image = "https://uzautomotors.com/images/uploads/2c2252e409368d0d3549beaa3e0651a4.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "CHEVROLET EQUINOX",
                            PricePerDay = 320000m,
                            Speed = 230,
                            Year = 2020
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6185),
                            Description = "The new Chevrolet Traverse has everything to make every kilometer special for you and your family. Up to 8 passenger seats and the most spacious luggage space in the class, the function of choosing a driving mode and an advanced all-wheel drive system, a solid appearance and a well-designed interior - this car is able to adapt to any task. Add to this the latest security technology, as well as additional features for your comfort, and you will understand why Traverse is worthy of your choice.",
                            GearType = 1,
                            Image = "https://blogmedia.dealerfire.com/wp-content/uploads/sites/1074/2019/12/2020-Honda-Ridgeline-exterior-side-shot-with-Obsidian-Blue-Pearl-paint-color-parked-on-a-beach-line-of-gravel-and-sand-next-to-the-ocean_o.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "CHEVROLET TRAVERSE",
                            PricePerDay = 315000m,
                            Speed = 220,
                            Year = 2020
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6200),
                            Description = "",
                            GearType = 0,
                            Image = "https://fichasmotor.com/images/chevrolet/chevrolet-traverse-i-3-6-v6-281-cv-awd-automatico.webp",
                            InUse = true,
                            IsDeleted = false,
                            Model = "CHEVROLET TRAVERSE",
                            PricePerDay = 280000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6215),
                            Description = "A full-size SUV that combines technology, performance, design and safety is all about it - the Chevrolet Trailblazer. If you need a car with a powerful engine for both travel and everyday life, then Trailblazer is a great choice",
                            GearType = 1,
                            Image = "https://uzautomotors.com/images/uploads/6be5fb769c9b8ef6509eb3f3a1fc497a.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "CHEVROLET TRAILBLAZER",
                            PricePerDay = 300000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6230),
                            Description = "",
                            GearType = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzsEfyLUAVg2o3cjhWRZ4el8z6T6dCU7SzmA&usqp=CAU",
                            InUse = false,
                            IsDeleted = false,
                            Model = "CHEVROLET TRAILBLAZER",
                            PricePerDay = 390000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6247),
                            Description = "The Impala continues to reign as the leading large sedan. Slide behind the wheel and you can see why. Roomy, supportive seats put you in the perfect position to access the intuitive controls. Despite its prodigious size, the Impala’s handling is responsive and secure.",
                            GearType = 2,
                            Image = "https://banner2.cleanpng.com/20180410/xrw/kisspng-2017-chevrolet-impala-2018-chevrolet-impala-chevro-chevrolet-5accd70885ac83.6020416415233738325475.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "Chevrolet Impala",
                            PricePerDay = 300000m,
                            Speed = 200,
                            Year = 2020
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6304),
                            Description = "",
                            GearType = 0,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW3yA6kh0qsD_IP65A3K9Ibsbkm1k8x2gaEQ&usqp=CAU",
                            InUse = false,
                            IsDeleted = false,
                            Model = "Chevrolet Impala",
                            PricePerDay = 280000m,
                            Speed = 200,
                            Year = 2018
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6324),
                            Description = "If appearance is important, then Lacetti is for you. Correct proportions, streamlined shapes, relief lines harmoniously combined in this car, which has a respectable interior and exterior. Lacetti comfortably accommodates five people in a modern laconic salon. The instrument panel features a sense of proportion and variety of options. The arrangement of the instruments with chrome elements is carefully thought out. Its driving qualities are thoroughly tested and perfected.",
                            GearType = 2,
                            Image = "https://uzautomotors.com/images/uploads/8c8ad114c16e10db77c7953a2afc5b62.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "CHEVROLET LACETTI",
                            PricePerDay = 200000m,
                            Speed = 280,
                            Year = 2020
                        },
                        new
                        {
                            Id = 21,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(6339),
                            Description = "in good condition",
                            GearType = 0,
                            Image = "https://uzautomotors.com/images/uploads/ca519572d01038ee51311f82f9384204.jpg",
                            InUse = false,
                            IsDeleted = false,
                            Model = "CHEVROLET LACETTI",
                            PricePerDay = 180000m,
                            Speed = 200,
                            Year = 2020
                        });
                });

            modelBuilder.Entity("Car2Go.Data.Models.CarRentDays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("CarRentDays");
                });

            modelBuilder.Entity("Car2Go.Data.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("Car2Go.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(1845),
                            IsDeleted = false,
                            Name = "Tashkent International Airport"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2730),
                            IsDeleted = false,
                            Name = "Chilanzar Subway Station"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2768),
                            IsDeleted = false,
                            Name = "Hilton Hotel"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2781),
                            IsDeleted = false,
                            Name = "Mega Planet"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2794),
                            IsDeleted = false,
                            Name = "North Train Station"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2810),
                            IsDeleted = false,
                            Name = "South Train Station"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2822),
                            IsDeleted = false,
                            Name = "Bunyodkor Stadium"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2835),
                            IsDeleted = false,
                            Name = "Oybek Subway Station"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2847),
                            IsDeleted = false,
                            Name = "Park Amir Temur"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2022, 6, 4, 9, 48, 44, 475, DateTimeKind.Utc).AddTicks(2860),
                            IsDeleted = false,
                            Name = "Buyuk Ipak Yoli Subway Station"
                        });
                });

            modelBuilder.Entity("Car2Go.Data.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PickUpLocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RentEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CarId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PickUpLocationId");

                    b.HasIndex("ReturnLocationId");

                    b.HasIndex("ReviewId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Car2Go.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CarId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Car2Go.Data.Models.Car", b =>
                {
                    b.HasOne("Car2Go.Data.Models.Dealer", "Dealer")
                        .WithMany("Cars")
                        .HasForeignKey("DealerId");
                });

            modelBuilder.Entity("Car2Go.Data.Models.CarRentDays", b =>
                {
                    b.HasOne("Car2Go.Data.Models.Car", "Car")
                        .WithMany("RentDays")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Car2Go.Data.Models.Order", b =>
                {
                    b.HasOne("Car2Go.Data.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car2Go.Data.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car2Go.Data.Models.Location", "PickUpLocation")
                        .WithMany()
                        .HasForeignKey("PickUpLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car2Go.Data.Models.Location", "ReturnLocation")
                        .WithMany()
                        .HasForeignKey("ReturnLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car2Go.Data.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId");
                });

            modelBuilder.Entity("Car2Go.Data.Models.Review", b =>
                {
                    b.HasOne("Car2Go.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car2Go.Data.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Car2Go.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Car2Go.Data.Models.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Car2Go.Data.Models.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Car2Go.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Car2Go.Data.Models.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Car2Go.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
